"""add reporting effort tracker tables

Revision ID: 0b87c8f59a0e
Revises: ce4a91039756
Create Date: 2025-08-13 13:38:38.840621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0b87c8f59a0e'
down_revision = 'ce4a91039756'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add department column to users table
    op.add_column('users', sa.Column('department', sa.String(length=50), nullable=True))
    
    # Create reporting_effort_items table
    op.create_table('reporting_effort_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reporting_effort_id', sa.Integer(), nullable=False),
        sa.Column('source_type', sa.String(length=50), nullable=True),
        sa.Column('source_id', sa.Integer(), nullable=True),
        sa.Column('source_item_id', sa.Integer(), nullable=True),
        sa.Column('item_type', postgresql.ENUM('TLF', 'Dataset', name='itemtype', create_type=False), nullable=False),
        sa.Column('item_subtype', sa.String(length=50), nullable=False),
        sa.Column('item_code', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True, default=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.ForeignKeyConstraint(['reporting_effort_id'], ['reporting_efforts.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('reporting_effort_id', 'item_type', 'item_subtype', 'item_code', name='uq_reporting_effort_item_unique')
    )
    op.create_index(op.f('ix_reporting_effort_items_item_type'), 'reporting_effort_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_reporting_effort_items_reporting_effort_id'), 'reporting_effort_items', ['reporting_effort_id'], unique=False)
    
    # Create reporting_effort_tlf_details table
    op.create_table('reporting_effort_tlf_details',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reporting_effort_item_id', sa.Integer(), nullable=False),
        sa.Column('title_id', sa.Integer(), nullable=True),
        sa.Column('population_flag_id', sa.Integer(), nullable=True),
        sa.Column('ich_category_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['reporting_effort_item_id'], ['reporting_effort_items.id'], ),
        sa.ForeignKeyConstraint(['title_id'], ['text_elements.id'], ),
        sa.ForeignKeyConstraint(['population_flag_id'], ['text_elements.id'], ),
        sa.ForeignKeyConstraint(['ich_category_id'], ['text_elements.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporting_effort_tlf_details_reporting_effort_item_id'), 'reporting_effort_tlf_details', ['reporting_effort_item_id'], unique=True)
    
    # Create reporting_effort_dataset_details table
    op.create_table('reporting_effort_dataset_details',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reporting_effort_item_id', sa.Integer(), nullable=False),
        sa.Column('label', sa.String(length=255), nullable=True),
        sa.Column('sorting_order', sa.Integer(), nullable=True),
        sa.Column('acronyms', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['reporting_effort_item_id'], ['reporting_effort_items.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporting_effort_dataset_details_reporting_effort_item_id'), 'reporting_effort_dataset_details', ['reporting_effort_item_id'], unique=True)
    
    # Create reporting_effort_item_footnotes junction table
    op.create_table('reporting_effort_item_footnotes',
        sa.Column('reporting_effort_item_id', sa.Integer(), nullable=False),
        sa.Column('footnote_id', sa.Integer(), nullable=False),
        sa.Column('sequence_number', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['reporting_effort_item_id'], ['reporting_effort_items.id'], ),
        sa.ForeignKeyConstraint(['footnote_id'], ['text_elements.id'], ),
        sa.PrimaryKeyConstraint('reporting_effort_item_id', 'footnote_id')
    )
    
    # Create reporting_effort_item_acronyms junction table
    op.create_table('reporting_effort_item_acronyms',
        sa.Column('reporting_effort_item_id', sa.Integer(), nullable=False),
        sa.Column('acronym_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['reporting_effort_item_id'], ['reporting_effort_items.id'], ),
        sa.ForeignKeyConstraint(['acronym_id'], ['text_elements.id'], ),
        sa.PrimaryKeyConstraint('reporting_effort_item_id', 'acronym_id')
    )
    
    # Create reporting_effort_item_tracker table
    op.create_table('reporting_effort_item_tracker',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reporting_effort_item_id', sa.Integer(), nullable=False),
        sa.Column('production_programmer_id', sa.Integer(), nullable=True),
        sa.Column('production_status', sa.String(length=50), nullable=True, default='not_started'),
        sa.Column('due_date', sa.Date(), nullable=True),
        sa.Column('priority', sa.String(length=50), nullable=True, default='medium'),
        sa.Column('qc_level', sa.String(length=50), nullable=True),
        sa.Column('qc_programmer_id', sa.Integer(), nullable=True),
        sa.Column('qc_status', sa.String(length=50), nullable=True, default='not_started'),
        sa.Column('qc_completion_date', sa.Date(), nullable=True),
        sa.Column('in_production_flag', sa.Boolean(), nullable=True, default=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.ForeignKeyConstraint(['production_programmer_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['qc_programmer_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['reporting_effort_item_id'], ['reporting_effort_items.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('reporting_effort_item_id', name='uq_tracker_item')
    )
    op.create_index(op.f('ix_reporting_effort_item_tracker_reporting_effort_item_id'), 'reporting_effort_item_tracker', ['reporting_effort_item_id'], unique=True)
    op.create_index(op.f('ix_reporting_effort_item_tracker_production_programmer_id'), 'reporting_effort_item_tracker', ['production_programmer_id'], unique=False)
    op.create_index(op.f('ix_reporting_effort_item_tracker_qc_programmer_id'), 'reporting_effort_item_tracker', ['qc_programmer_id'], unique=False)
    
    # Create reporting_effort_tracker_comments table
    op.create_table('reporting_effort_tracker_comments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tracker_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('parent_comment_id', sa.Integer(), nullable=True),
        sa.Column('comment_text', sa.Text(), nullable=False),
        sa.Column('comment_type', sa.String(length=50), nullable=True),
        sa.Column('comment_category', sa.String(length=50), nullable=True, default='general'),
        sa.Column('is_pinned', sa.Boolean(), nullable=True, default=False),
        sa.Column('is_edited', sa.Boolean(), nullable=True, default=False),
        sa.Column('edited_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.ForeignKeyConstraint(['parent_comment_id'], ['reporting_effort_tracker_comments.id'], ),
        sa.ForeignKeyConstraint(['tracker_id'], ['reporting_effort_item_tracker.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporting_effort_tracker_comments_tracker_id'), 'reporting_effort_tracker_comments', ['tracker_id'], unique=False)
    op.create_index(op.f('ix_reporting_effort_tracker_comments_user_id'), 'reporting_effort_tracker_comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_reporting_effort_tracker_comments_comment_type'), 'reporting_effort_tracker_comments', ['comment_type'], unique=False)
    
    # Create audit_log table
    op.create_table('audit_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('table_name', sa.String(length=100), nullable=False),
        sa.Column('record_id', sa.Integer(), nullable=False),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('changes_json', sa.Text(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_table_name'), 'audit_log', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_log_record_id'), 'audit_log', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop tables in reverse order
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_record_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_table_name'), table_name='audit_log')
    op.drop_table('audit_log')
    
    op.drop_index(op.f('ix_reporting_effort_tracker_comments_comment_type'), table_name='reporting_effort_tracker_comments')
    op.drop_index(op.f('ix_reporting_effort_tracker_comments_user_id'), table_name='reporting_effort_tracker_comments')
    op.drop_index(op.f('ix_reporting_effort_tracker_comments_tracker_id'), table_name='reporting_effort_tracker_comments')
    op.drop_table('reporting_effort_tracker_comments')
    
    op.drop_index(op.f('ix_reporting_effort_item_tracker_qc_programmer_id'), table_name='reporting_effort_item_tracker')
    op.drop_index(op.f('ix_reporting_effort_item_tracker_production_programmer_id'), table_name='reporting_effort_item_tracker')
    op.drop_index(op.f('ix_reporting_effort_item_tracker_reporting_effort_item_id'), table_name='reporting_effort_item_tracker')
    op.drop_table('reporting_effort_item_tracker')
    
    op.drop_table('reporting_effort_item_acronyms')
    op.drop_table('reporting_effort_item_footnotes')
    
    op.drop_index(op.f('ix_reporting_effort_dataset_details_reporting_effort_item_id'), table_name='reporting_effort_dataset_details')
    op.drop_table('reporting_effort_dataset_details')
    
    op.drop_index(op.f('ix_reporting_effort_tlf_details_reporting_effort_item_id'), table_name='reporting_effort_tlf_details')
    op.drop_table('reporting_effort_tlf_details')
    
    op.drop_index(op.f('ix_reporting_effort_items_reporting_effort_id'), table_name='reporting_effort_items')
    op.drop_index(op.f('ix_reporting_effort_items_item_type'), table_name='reporting_effort_items')
    op.drop_table('reporting_effort_items')
    
    # Remove department column from users table
    op.drop_column('users', 'department')
    
    # ### end Alembic commands ###