"""Add reporting effort lock fields and history table

Revision ID: 12812f1105e7
Revises: 4d777ce11e55
Create Date: 2026-01-12 17:29:04.866667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12812f1105e7'
down_revision = '4d777ce11e55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add lock fields to reporting_efforts table
    op.add_column('reporting_efforts', sa.Column('is_locked', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('reporting_efforts', sa.Column('locked_at', sa.DateTime(), nullable=True))
    op.add_column('reporting_efforts', sa.Column('locked_by_id', sa.Integer(), nullable=True))
    op.add_column('reporting_efforts', sa.Column('lock_reason', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'reporting_efforts', 'users', ['locked_by_id'], ['id'])
    
    # Create reporting_effort_lock_history table
    op.create_table(
        'reporting_effort_lock_history',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('reporting_effort_id', sa.Integer(), nullable=False),
        sa.Column('performed_by_id', sa.Integer(), nullable=False),
        sa.Column('action', sa.Enum('LOCK', 'UNLOCK', name='lockaction'), nullable=False),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['reporting_effort_id'], ['reporting_efforts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'])
    )
    op.create_index('ix_reporting_effort_lock_history_reporting_effort_id', 'reporting_effort_lock_history', ['reporting_effort_id'])
    op.create_index('ix_reporting_effort_lock_history_performed_by_id', 'reporting_effort_lock_history', ['performed_by_id'])
    op.create_index('ix_reporting_effort_lock_history_created_at', 'reporting_effort_lock_history', ['created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop reporting_effort_lock_history table
    op.drop_index('ix_reporting_effort_lock_history_created_at', table_name='reporting_effort_lock_history')
    op.drop_index('ix_reporting_effort_lock_history_performed_by_id', table_name='reporting_effort_lock_history')
    op.drop_index('ix_reporting_effort_lock_history_reporting_effort_id', table_name='reporting_effort_lock_history')
    op.drop_table('reporting_effort_lock_history')
    
    # Remove lock fields from reporting_efforts table
    op.drop_constraint(None, 'reporting_efforts', type_='foreignkey')
    op.drop_column('reporting_efforts', 'lock_reason')
    op.drop_column('reporting_efforts', 'locked_by_id')
    op.drop_column('reporting_efforts', 'locked_at')
    op.drop_column('reporting_efforts', 'is_locked')
    
    # Drop the lockaction enum type
    sa.Enum('LOCK', 'UNLOCK', name='lockaction').drop(op.get_bind())
    # ### end Alembic commands ###