"""Create new TNFP and acronym tables with proper relationships

Revision ID: 473053e83a5b
Revises: c22f57d3ab22
Create Date: 2025-07-31 10:15:23.536944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473053e83a5b'
down_revision = 'c22f57d3ab22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum type if it doesn't exist
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE textelementtype AS ENUM ('title', 'footnote', 'population_set');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Create text_elements table
    op.create_table(
        'text_elements',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('type', sa.Enum('title', 'footnote', 'population_set', name='textelementtype', create_type=False), nullable=False),
        sa.Column('label', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_elements_type'), 'text_elements', ['type'], unique=False)

    # Create acronyms table
    op.create_table(
        'acronyms',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('key', sa.String(50), nullable=False),
        sa.Column('value', sa.String(255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key', name='uq_acronym_key')
    )
    op.create_index(op.f('ix_acronyms_key'), 'acronyms', ['key'], unique=True)
    op.create_index(op.f('ix_acronyms_value'), 'acronyms', ['value'], unique=False)

    # Create acronym_sets table
    op.create_table(
        'acronym_sets',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', name='uq_acronym_set_name')
    )
    op.create_index(op.f('ix_acronym_sets_name'), 'acronym_sets', ['name'], unique=True)

    # Create acronym_set_members table
    op.create_table(
        'acronym_set_members',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('acronym_set_id', sa.Integer(), nullable=False),
        sa.Column('acronym_id', sa.Integer(), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=False, default=0),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['acronym_id'], ['acronyms.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['acronym_set_id'], ['acronym_sets.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('acronym_set_id', 'acronym_id', name='uq_acronym_set_member')
    )
    op.create_index(op.f('ix_acronym_set_members_acronym_id'), 'acronym_set_members', ['acronym_id'], unique=False)
    op.create_index(op.f('ix_acronym_set_members_acronym_set_id'), 'acronym_set_members', ['acronym_set_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop tables in reverse order (respecting foreign key constraints)
    op.drop_table('acronym_set_members')
    op.drop_table('acronym_sets')
    op.drop_table('acronyms')
    op.drop_table('text_elements')
    
    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS textelementtype")
    
    # ### end Alembic commands ###