"""Add error_log table

Revision ID: 4d777ce11e55
Revises: 58b81d3ab34f
Create Date: 2026-01-12 10:13:50.186495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d777ce11e55'
down_revision = '58b81d3ab34f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('component_name', sa.String(length=200), nullable=True),
    sa.Column('browser_info', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_log_correlation_id'), 'error_log', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_error_log_created_at'), 'error_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_error_log_error_type'), 'error_log', ['error_type'], unique=False)
    op.create_index(op.f('ix_error_log_request_path'), 'error_log', ['request_path'], unique=False)
    op.create_index(op.f('ix_error_log_severity'), 'error_log', ['severity'], unique=False)
    op.create_index(op.f('ix_error_log_source'), 'error_log', ['source'], unique=False)
    op.create_index(op.f('ix_error_log_user_id'), 'error_log', ['user_id'], unique=False)
    op.drop_index(op.f('ix_dataset_details_ig_version_id'), table_name='reporting_effort_dataset_details')
    op.create_index(op.f('ix_reporting_effort_dataset_details_ig_version_id'), 'reporting_effort_dataset_details', ['ig_version_id'], unique=False)
    op.drop_index(op.f('ix_reporting_effort_milestones_display_order'), table_name='reporting_effort_milestones')
    op.drop_index(op.f('ix_reporting_effort_milestones_due_date'), table_name='reporting_effort_milestones')
    op.drop_index(op.f('ix_reporting_effort_milestones_is_completed'), table_name='reporting_effort_milestones')
    op.drop_index(op.f('ix_reporting_effort_phases_display_order'), table_name='reporting_effort_phases')
    op.drop_index(op.f('ix_user_study_roles_role'), table_name='user_study_roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_study_roles_role'), 'user_study_roles', ['role'], unique=False)
    op.create_index(op.f('ix_reporting_effort_phases_display_order'), 'reporting_effort_phases', ['display_order'], unique=False)
    op.create_index(op.f('ix_reporting_effort_milestones_is_completed'), 'reporting_effort_milestones', ['is_completed'], unique=False)
    op.create_index(op.f('ix_reporting_effort_milestones_due_date'), 'reporting_effort_milestones', ['due_date'], unique=False)
    op.create_index(op.f('ix_reporting_effort_milestones_display_order'), 'reporting_effort_milestones', ['display_order'], unique=False)
    op.drop_index(op.f('ix_reporting_effort_dataset_details_ig_version_id'), table_name='reporting_effort_dataset_details')
    op.create_index(op.f('ix_dataset_details_ig_version_id'), 'reporting_effort_dataset_details', ['ig_version_id'], unique=False)
    op.drop_index(op.f('ix_error_log_user_id'), table_name='error_log')
    op.drop_index(op.f('ix_error_log_source'), table_name='error_log')
    op.drop_index(op.f('ix_error_log_severity'), table_name='error_log')
    op.drop_index(op.f('ix_error_log_request_path'), table_name='error_log')
    op.drop_index(op.f('ix_error_log_error_type'), table_name='error_log')
    op.drop_index(op.f('ix_error_log_created_at'), table_name='error_log')
    op.drop_index(op.f('ix_error_log_correlation_id'), table_name='error_log')
    op.drop_table('error_log')
    # ### end Alembic commands ###