"""Add users table with username and role columns

Revision ID: 72383a245505
Revises: d3f89a2c4b56
Create Date: 2025-08-11 17:29:23.442301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72383a245505'
down_revision = 'd3f89a2c4b56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###