"""add_reporting_efforts_table

Revision ID: 9210364e4641
Revises: a0b65bfec576
Create Date: 2025-07-30 14:15:17.224968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9210364e4641'
down_revision = 'a0b65bfec576'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporting_efforts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('database_release_id', sa.Integer(), nullable=False),
    sa.Column('database_release_label', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['database_release_id'], ['database_releases.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_reporting_efforts_database_release_id'), 'reporting_efforts', ['database_release_id'], unique=False)
    op.create_index(op.f('ix_reporting_efforts_id'), 'reporting_efforts', ['id'], unique=False)
    op.create_index(op.f('ix_reporting_efforts_study_id'), 'reporting_efforts', ['study_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reporting_efforts_study_id'), table_name='reporting_efforts')
    op.drop_index(op.f('ix_reporting_efforts_id'), table_name='reporting_efforts')
    op.drop_index(op.f('ix_reporting_efforts_database_release_id'), table_name='reporting_efforts')
    op.drop_table('reporting_efforts')
    # ### end Alembic commands ###