"""Add timestamps to existing tables and create new TNFP and acronym tables

Revision ID: c22f57d3ab22
Revises: 9210364e4641
Create Date: 2025-07-31 10:13:57.923432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22f57d3ab22'
down_revision = '9210364e4641'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add timestamp columns with default values for existing records
    current_timestamp = sa.text("CURRENT_TIMESTAMP")
    
    # Add timestamp columns to database_releases
    op.add_column('database_releases', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=current_timestamp))
    op.add_column('database_releases', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=current_timestamp))
    
    # Add timestamp columns to reporting_efforts  
    op.add_column('reporting_efforts', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=current_timestamp))
    op.add_column('reporting_efforts', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=current_timestamp))
    
    # Add unique constraint for reporting efforts
    op.create_unique_constraint('uq_database_release_reporting_effort_label', 'reporting_efforts', ['database_release_id', 'database_release_label'])
    
    # Add timestamp columns to studies
    op.add_column('studies', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=current_timestamp))
    op.add_column('studies', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=current_timestamp))
    
    # Remove server defaults after setting initial values (the application will handle defaults going forward)
    op.alter_column('database_releases', 'created_at', server_default=None)
    op.alter_column('database_releases', 'updated_at', server_default=None)
    op.alter_column('reporting_efforts', 'created_at', server_default=None)
    op.alter_column('reporting_efforts', 'updated_at', server_default=None)
    op.alter_column('studies', 'created_at', server_default=None)
    op.alter_column('studies', 'updated_at', server_default=None)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studies', 'updated_at')
    op.drop_column('studies', 'created_at')
    op.drop_constraint('uq_database_release_reporting_effort_label', 'reporting_efforts', type_='unique')
    op.drop_column('reporting_efforts', 'updated_at')
    op.drop_column('reporting_efforts', 'created_at')
    op.drop_column('database_releases', 'updated_at')
    op.drop_column('database_releases', 'created_at')
    # ### end Alembic commands ###