"""Remove study_id from package_items and add ich_category

Revision ID: ce4a91039756
Revises: 72383a245505
Create Date: 2025-08-11 23:07:59.784931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4a91039756'
down_revision = '72383a245505'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_items_study_id'), table_name='package_items')
    op.drop_constraint(op.f('package_items_study_id_fkey'), 'package_items', type_='foreignkey')
    op.drop_column('package_items', 'study_id')
    op.add_column('package_tlf_details', sa.Column('ich_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'package_tlf_details', 'text_elements', ['ich_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'package_tlf_details', type_='foreignkey')
    op.drop_column('package_tlf_details', 'ich_category_id')
    op.add_column('package_items', sa.Column('study_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('package_items_study_id_fkey'), 'package_items', 'studies', ['study_id'], ['id'])
    op.create_index(op.f('ix_package_items_study_id'), 'package_items', ['study_id'], unique=False)
    # ### end Alembic commands ###