"""Add feature_requests table

Revision ID: ebe30a019c99
Revises: add_biostat_review
Create Date: 2026-01-21 15:37:02.684710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe30a019c99'
down_revision = 'add_biostat_review'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_requests_category'), 'feature_requests', ['category'], unique=False)
    op.create_index(op.f('ix_feature_requests_created_at'), 'feature_requests', ['created_at'], unique=False)
    op.create_index('ix_feature_requests_status', 'feature_requests', ['status'], unique=False)
    op.create_index(op.f('ix_feature_requests_tenant_id'), 'feature_requests', ['tenant_id'], unique=False)
    op.create_index('ix_feature_requests_tenant_status', 'feature_requests', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_feature_requests_tenant_user', 'feature_requests', ['tenant_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_feature_requests_user_id'), 'feature_requests', ['user_id'], unique=False)
    op.drop_index(op.f('ix_tracker_biostat_reviewer_id'), table_name='reporting_effort_item_tracker')
    op.drop_index(op.f('ix_tracker_biostat_status'), table_name='reporting_effort_item_tracker')
    op.drop_index(op.f('ix_tracker_unresolved_biostat_count'), table_name='reporting_effort_item_tracker')
    op.create_index(op.f('ix_reporting_effort_item_tracker_biostat_reviewer_id'), 'reporting_effort_item_tracker', ['biostat_reviewer_id'], unique=False)
    op.create_index(op.f('ix_reporting_effort_item_tracker_biostat_status'), 'reporting_effort_item_tracker', ['biostat_status'], unique=False)
    op.create_index(op.f('ix_reporting_effort_item_tracker_unresolved_biostat_comment_count'), 'reporting_effort_item_tracker', ['unresolved_biostat_comment_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reporting_effort_item_tracker_unresolved_biostat_comment_count'), table_name='reporting_effort_item_tracker')
    op.drop_index(op.f('ix_reporting_effort_item_tracker_biostat_status'), table_name='reporting_effort_item_tracker')
    op.drop_index(op.f('ix_reporting_effort_item_tracker_biostat_reviewer_id'), table_name='reporting_effort_item_tracker')
    op.create_index(op.f('ix_tracker_unresolved_biostat_count'), 'reporting_effort_item_tracker', ['unresolved_biostat_comment_count'], unique=False)
    op.create_index(op.f('ix_tracker_biostat_status'), 'reporting_effort_item_tracker', ['biostat_status'], unique=False)
    op.create_index(op.f('ix_tracker_biostat_reviewer_id'), 'reporting_effort_item_tracker', ['biostat_reviewer_id'], unique=False)
    op.drop_index(op.f('ix_feature_requests_user_id'), table_name='feature_requests')
    op.drop_index('ix_feature_requests_tenant_user', table_name='feature_requests')
    op.drop_index('ix_feature_requests_tenant_status', table_name='feature_requests')
    op.drop_index(op.f('ix_feature_requests_tenant_id'), table_name='feature_requests')
    op.drop_index('ix_feature_requests_status', table_name='feature_requests')
    op.drop_index(op.f('ix_feature_requests_created_at'), table_name='feature_requests')
    op.drop_index(op.f('ix_feature_requests_category'), table_name='feature_requests')
    op.drop_table('feature_requests')
    # ### end Alembic commands ###